apiVersion: v1
kind: Service
metadata:
  name: daview
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: com.tale.daview
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daview
spec:
  selector:
    matchLabels:
      app: com.tale.daview
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: com.tale.daview
    spec:
      containers:
        - image: tale.me/library/daview:latest
          name: daview
          env:
            - name: HOST
              value: '0.0.0.0'
            - name: PORT
              value: '3000'
            - name: PROXY_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: daview-env
                  key: PROXY_ENDPOINT
            - name: PROXY_LOGIN
              valueFrom:
                secretKeyRef:
                  name: daview-env
                  key: PROXY_LOGIN
            - name: PROXY_USERS
              valueFrom:
                secretKeyRef:
                  name: daview-env
                  key: PROXY_USERS
            - name: PROXY_SECRET
              valueFrom:
                secretKeyRef:
                  name: daview-env
                  key: PROXY_SECRET
